### ISSUE TITLE
1.20.6 Sand Duper No Work

### ISSUE THREAD

**Issue by thecrackzipple4115451** [Hynse/FoliaFlow#24]
Hello, we use Folia for MC 1.20.6 
All settings for duper is allow 
and we have add FoliaFlow with default settings

But this Sand duper no work.. i have testwith manual sand duper with a gate no work too 

Tutorial : 
https://www.youtube.com/watch?v=S4HISFFdnuc

And this is the Paper config : 

unsupported-settings:
  allow-headless-pistons: true
  allow-permanent-block-break-exploits: true
  allow-piston-duplication: true
  allow-tripwire-disarming-exploits: true
  allow-unsafe-end-portal-teleportation: true
  compression-format: ZLIB
  perform-username-validation: true

**Comment by MidnightTale** [comment]
are you on Foliaflow version 2.4 ?

**Comment by MidnightTale** [comment]
Sorry but this issue cannot be fixed with a plugin and requires a server patch.

The dupe mechanic you're using causes the block to become a falling block. On the 1 tick, it has no velocity, so the plugin cannot determine the direction the block is moving. It only acquires velocity on the 2 tick. While we could add a delay to check for velocity, this solution would break other dupe mechanic that rely on the falling block having an initial velocity.

**Comment by thecrackzipple4115451** [comment]
Do you have idea how ? or a sand duper tutorial work with Folia ? 

Do you have idea how edit ?

**Comment by MidnightTale** [comment]
normal duper mechanic any design you using collector get patch in 1.21

**Comment by thecrackzipple4115451** [comment]
So, for now in 1.20.6 no solution ? FoliaFlow so : not work

**Comment by MidnightTale** [comment]
> Sorry but this issue cannot be fixed with a plugin and requires a server patch.
> 
> The dupe mechanic you're using causes the block to become a falling block. On the 1 tick, it has no velocity, so the plugin cannot determine the direction the block is moving. It only acquires velocity on the 2 tick. While we could add a delay to check for velocity, this solution would break other dupe mechanic that rely on the falling block having an initial velocity.

yes as i said early this design  https://www.youtube.com/watch?v=S4HISFFdnuc can't fix with **plugin.**
